export const defaultDomains = [
  {
    id: 'portfolio',
    prefix: 'me',
    label: 'Portfolio',
    href: 'https://dikshantyadav.in',
    lineColor: '#ffffff',
    icon: 'globe',
  },
  {
    id: 'telegram',
    prefix: 't',
    label: 'Telegram',
    href: 'https://t.dikshantyadav.in',
    lineColor: '#0088cc',
    icon: 'send',
  },
  {
    id: 'instagram',
    prefix: 'i',
    label: 'Instagram',
    href: 'https://i.dikshantyadav.in',
    lineColor: '#e4405f',
    icon: 'instagram',
  },
  {
    id: 'github',
    prefix: 'g',
    label: 'GitHub',
    href: 'https://g.dikshantyadav.in',
    lineColor: '#ffffff',
    icon: 'github',
  },
  {
    id: 'whatsapp',
    prefix: 'w',
    label: 'WhatsApp',
    href: 'https://w.dikshantyadav.in',
    lineColor: '#25d366',
    icon: 'message-circle',
  },
  {
    id: 'youtube',
    prefix: 'yt',
    label: 'YouTube',
    href: 'https://yt.dikshantyadav.in',
    lineColor: '#ff0000',
    icon: 'youtube',
  },
];
