const services = [
  {
    id: '00-1',
    title: 'WEB DESIGN',
    features: [
      '/ MODERN LAYOUTS',
      '/ RESPONSIVE DESIGN',
      '/ SEO-FRIENDLY STRUCTURE',
      '/ CLEAR NAVIGATION',
      '/ VISUAL STORYTELLING',
    ],
    description:
      'I CREATE WEBSITES THAT STAND OUT FROM THE COMPETITION AND BRING REAL VALUE TO BUSINESSES. EACH PROJECT COMBINES CREATIVITY AND FUNCTIONALITY TO DELIVER THE BEST DIGITAL SOLUTIONS.',
  },
  {
    id: '00-2',
    title: 'UX/UI DESIGN',
    features: [
      '/ USER RESEARCH',
      '/ INTERFACE DESIGN',
      '/ PROTOTYPING & TESTING',
      '/ DESIGN SYSTEMS',
      '/ CONVERSION FOCUSED',
    ],
    description:
      'CRAFTING INTERFACES THAT FEEL NATURAL AND INTUITIVE. EVERY PIXEL IS PLACED WITH PURPOSE, EVERY INTERACTION DESIGNED TO GUIDE USERS TOWARD MEANINGFUL OUTCOMES.',
  },
  {
    id: '00-3',
    title: 'CREATIVE DESIGN',
    features: [
      '/ CREATIVE CONCEPTS',
      '/ ART DIRECTION',
      '/ VISUAL SYSTEMS',
      '/ MOTION & INTERACTION',
    ],
    description:
      'CREATIVE DESIGN BUILT TO CREATE DISTINCT VISUAL EXPERIENCES THAT CONNECT BRAND, PRODUCT, AND DIGITAL INTERACTION INTO ONE COHESIVE LANGUAGE.',
  },
  {
    id: '00-4',
    title: 'PRODUCT AND APP DESIGN',
    features: [
      '/ MOBILE & WEB APPS',
      '/ DESIGN SYSTEMS',
      '/ COMPLEX INTERACTIONS',
      '/ SCALABLE SOLUTIONS',
    ],
    description:
      'PRODUCT AND APP DESIGN FOCUSED ON SIMPLICITY, CONSISTENCY, AND GROWTH — CRAFTED TO DELIVER THE BEST DIGITAL SOLUTIONS.',
  },
  {
    id: '00-5',
    title: 'DEVELOPMENT',
    features: [
      '/ FRONTEND ENGINEERING',
      '/ RESPONSIVE BUILDOUTS',
      '/ ANIMATION & INTERACTION',
      '/ PERFORMANCE OPTIMIZED',
    ],
    description:
      'BRINGING DESIGNS TO LIFE WITH CLEAN, PERFORMANT CODE. FROM SMOOTH ANIMATIONS TO SOLID ARCHITECTURE — EVERY DETAIL EXECUTED WITH PRECISION.',
  },
];

export default services;
